# Exercise 1a - NumPy Basics

### Understanding NumPy and ndarrays
NumPy is the foundational package for numerical computing in Python. It provides the ndarray object, which is an efficient, N-dimensional array structure.

**Why use NumPy?**
- It enables fast numerical computations using vectorized operations.
- Memory-efficient compared to regular Python lists.
- Essential for data science, machine learning, and image processing tasks.

**Key Features of ndarrays:**
- Homogeneous data types (all elements must be the same type).
- Support for broadcasting and shape manipulation.
- Built-in mathematical functions for arrays.

In this exercise, you'll create and manipulate ndarrays using NumPy.


In [1]:
import numpy as np

# Create a 1D array with values from 0 to 9
a = np.arange(10)
print("Original array:", a)

# Reshape to a 2D array (2 rows, 5 columns)
b = a.reshape(2, 5)
print("Reshaped array (2x5):", b)

# Multiply all elements by 3
c = b * 3
print("Array multiplied by 3:", c)


Original array: [0 1 2 3 4 5 6 7 8 9]
Reshaped array (2x5): [[0 1 2 3 4]
 [5 6 7 8 9]]
Array multiplied by 3: [[ 0  3  6  9 12]
 [15 18 21 24 27]]


### Practice
Apply what you've learned by modifying the code or writing your own version.

- Try creating a different shape of ndarray.
- Filter DataFrame rows using a different condition.
- Fill missing values using the median instead of the mean.
- Create a new column based on existing ones.

In [ ]:
# Your practice code here


### Broadcasting and Arithmetic Operations in NumPy
**Broadcasting** is a powerful NumPy feature that allows arithmetic operations between arrays of different shapes.

**Use Cases:**
- Adding a constant to every element in a matrix.
- Applying operations across rows or columns efficiently.

In this exercise, you'll perform addition and multiplication using broadcasting in NumPy arrays.


In [2]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Broadcast a scalar value to all elements
array_plus_10 = array + 10

# Broadcast a 1D array across rows
multiplier = np.array([1, 2, 3])
result = array * multiplier

print("Original Array:\n", array)
print("Array + 10:\n", array_plus_10)
print("Array * [1, 2, 3]:\n", result)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array + 10:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Array * [1, 2, 3]:
 [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


### Practice
Apply what you've learned by modifying the code or writing your own version.

- Try creating a different shape of ndarray.
- Filter DataFrame rows using a different condition.
- Fill missing values using the median instead of the mean.
- Create a new column based on existing ones.

In [ ]:
# Your practice code here
